/* Only local mock endpoints. No real microphone, speech, devices or messages. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const base=process.env.UI_URL||'http://127.0.0.1:8773';
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[],checks=[];
  page.on('pageerror',e=>errors.push(e.message));
  async function request(body){const r=await page.request.post(base+'/api/assistive/action',{data:body});const value=await r.json();assert.equal(value.ok,true,JSON.stringify(value));return value;}
  async function shot(name){if(process.env.UI_ARTIFACTS){fs.mkdirSync(process.env.UI_ARTIFACTS,{recursive:true});await page.screenshot({path:path.join(process.env.UI_ARTIFACTS,name),fullPage:true});}}
  try{
    await page.goto(base,{waitUntil:'networkidle'});
    await page.locator('#view-assistive').waitFor({state:'visible'});
    await page.locator('#care-catalog article').first().waitFor();
    assert.ok(await page.locator('#care-catalog article').count()>=49);
    assert.match(await page.locator('#care-mode').innerText(),/软件演示/);
    checks.push('home landing and scenario catalog render; software mode remains visible');
    const title='浏览器提醒'+Date.now();
    const created=await request({op:'reminder.create',title,delay_seconds:0});
    await page.waitForTimeout(1200);
    await page.locator('#care-refresh').click();
    const reminder=page.locator('#care-reminders article').filter({hasText:title});
    await reminder.getByRole('button',{name:'我已知晓'}).click();
    await page.waitForFunction(title=>[...document.querySelectorAll('#care-reminders article')].some(n=>n.textContent.includes(title)&&n.textContent.includes('已确认')),title);
    checks.push('due reminder acknowledges through persistent service');
    await page.locator('#care-help-category').selectOption('bathing');
    await page.locator('#care-help-note').fill('需要人工帮助，尚未联系任何人');
    await page.locator('#care-help-form button').click();
    const help=page.locator('#care-assistance article').filter({hasText:'需要人工帮助，尚未联系任何人'}).first();
    await help.waitFor();
    await help.getByRole('button',{name:'本人确认有人回应'}).click();
    await page.waitForTimeout(100);
    await help.getByRole('button',{name:'本人确认已解决'}).click();
    await page.waitForFunction(()=>document.querySelector('#care-assistance').textContent.includes('本人报告已解决'));
    checks.push('human assistance creation and locally attributed acknowledgment/resolution');
    await page.locator('#care-need-text').fill('测试纸巾');
    await page.locator('#care-need-form button').click();
    const need=page.locator('#care-needs article').filter({hasText:'测试纸巾'}).first();
    await need.getByRole('button',{name:'已经备好'}).click();
    await need.getByRole('button',{name:'恢复待准备'}).waitFor();
    await page.locator('#care-routines').getByRole('button',{name:'晨间准备',exact:true}).click();
    await page.locator('#care-checklists article').first().waitFor();
    await page.locator('#care-checklists article').first().getByRole('button').first().click();
    await page.waitForFunction(()=>document.querySelector('#care-checklists').textContent.includes('✓'));
    checks.push('supplies and daily routine checklist save user confirmations');
    await page.locator('#care-checkin-status').selectOption('need_help');
    await page.locator('#care-checkin-form button').click();
    await page.waitForFunction(()=>document.querySelector('#care-checkins').textContent.includes('需要帮助'));
    await page.locator('#care-device-form button').click();
    await page.waitForFunction(()=>document.querySelector('#care-robot').textContent.includes('succeeded'));
    await page.locator('#care-delivery-form button').click();
    await page.locator('#care-draft').getByRole('button',{name:'确认执行取送计划'}).click();
    await page.waitForFunction(()=>{const s=window.PatrolUI.getSnapshot();return s?.state==='succeeded'&&s.mission?.results?.at(-1)?.kind==='handover_object';});
    const state=await(await page.request.get(base+'/api/state')).json();
    assert.equal(state.mission.results.at(-1).kind,'handover_object');
    assert.equal(state.mission.results.at(-1).simulated,true);
    checks.push('household readback and confirmed delivery reach simulated receipt');
    await page.locator('#care-large').click();
    await page.locator('#care-contrast').click();
    await page.reload({waitUntil:'networkidle'});
    assert.equal(await page.locator('#care-large').getAttribute('aria-pressed'),'true');
    assert.equal(await page.locator('#care-contrast').getAttribute('aria-pressed'),'true');
    await page.locator('#care-scan').click();
    assert.equal(await page.locator('.care-scan-target').count(),1);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.care-scan-target').count(),0);
    await page.locator('#care-aac').getByRole('button',{name:'请等一下',exact:true}).click();
    assert.equal(await page.locator('#care-phrase').innerText(),'请等一下');
    checks.push('large text and contrast persist; switch scan exits; AAC displays without auto speech');
    await page.locator('#care-large').click();await page.locator('#care-contrast').click();
    await shot('v5-assistive-desktop.png');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    await page.locator('#care-filter').fill('如厕');
    assert.equal(await page.locator('#care-catalog article').count(),1);
    await shot('v5-assistive-mobile.png');
    checks.push('390px layout has no horizontal overflow and catalog filtering works');
    assert.deepEqual(errors,[]);
    const result={ok:true,scope:'local_mock_only',checkpoints:checks,page_errors:errors};
    if(process.env.UI_REPORT)fs.writeFileSync(process.env.UI_REPORT,JSON.stringify(result,null,2));
    console.log(JSON.stringify(result));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
