/* Application QA against an explicitly running localhost mock service.
   No real microphone, speaker, robot or paid API is used. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const url=process.env.UI_URL||'http://127.0.0.1:8773',checkpoints=[];
async function run(){
  const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],network=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('response',response=>{if(response.status()>=400)network.push([response.status(),response.url()]);});
  const snapshot=await(await page.request.get(url+'/api/state')).json();assert.equal(snapshot.mode,'mock');
  const switchView=async view=>{await page.locator(`[data-view="${view}"]:visible`).first().click();await page.locator(`#view-${view}`).waitFor({state:'visible'});};
  const postClick=async(suffix,locator)=>{const [response]=await Promise.all([page.waitForResponse(response=>response.url().endsWith(suffix)&&['POST','PUT'].includes(response.request().method())),locator.click()]);const value=await response.json();assert.equal(value.ok,true,JSON.stringify(value));return value;};
  const shot=async name=>{if(process.env.UI_ARTIFACTS){fs.mkdirSync(process.env.UI_ARTIFACTS,{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(process.env.UI_ARTIFACTS,name),fullPage:true,animations:'disabled'});}};
  try{
    await page.goto(url+"/#mission",{waitUntil:'networkidle'});await page.getByText('服务已连接',{exact:true}).waitFor();
    assert.equal(await page.evaluate(()=>window.PatrolStreamingVoice.state),'idle');
    await switchView('queue');await postClick('/api/queue/control',page.locator('#queue-pause'));
    await page.locator('#queue-text').fill('去前台');await page.locator('#queue-time').fill('2030-01-01T09:00');await page.locator('#queue-priority').fill('73');
    const queued=await postClick('/api/queue',page.locator('#queue-form button[type=submit]'));assert.equal(queued.job.priority,73);assert.equal(queued.job.status,'queued');
    await page.locator(`[data-job-id="${queued.job.id}"]`).getByRole('button',{name:'取消这条调度'}).click();await page.locator(`[data-job-id="${queued.job.id}"]`).getByText(/cancelled · 优先级 73/).waitFor();checkpoints.push('future queue creation, priority, pause and cancellation use real mock backend');

    await switchView('workflows');await page.locator('#workflow-name').fill('V3界面回归搜索');
    let plan=await postClick('/api/workflow/preview',page.locator('#workflow-preview'));assert.equal(plan.plan.steps.length,7);assert.equal(plan.plan.metadata.goal.object_name,'水杯');
    const template=await postClick('/api/templates',page.locator('#template-save'));const templateId=template.template.id;await page.getByText('模板已保存。',{exact:true}).waitFor();
    await page.locator('#workflow-name').fill('V3界面回归搜索修订');await postClick(`/api/templates/${templateId}`,page.locator('#template-save'));
    await postClick('/api/workflow/submit',page.locator('#workflow-submit'));await page.waitForFunction(()=>document.querySelector('#mission-state').textContent==='任务完成',null,{timeout:20000});
    await page.locator('#mission-report').getByText(/目标结果：已达成/).waitFor();checkpoints.push('workflow compile, template create/update and goal-aware execution pass');
    await switchView('memory');await page.locator('#memory-object').fill('水杯');await page.locator('#memory-form button').click();await page.locator('#memory-results').getByText(/水杯/).first().waitFor();await page.locator('#memory-results .record-card').first().getByRole('button',{name:'建立复查草稿'}).click();await page.locator('#view-workflows').waitFor({state:'visible'});assert.equal(await page.locator('#workflow-nodes>.workflow-node').count(),2);checkpoints.push('historic observations show evidence and create a reviewable recheck draft');

    await page.locator('#workflow-new').click();await page.locator('#workflow-name').fill('V3表单循环');await page.locator('#workflow-add-type').selectOption('repeat');await page.locator('#workflow-add').click();let repeat=page.locator('#workflow-nodes>.workflow-node').first();await repeat.getByLabel('循环次数').fill('2');await repeat.getByRole('button',{name:'添加子节点',exact:true}).click();let child=repeat.locator('.node-children .workflow-node');await child.getByLabel('技能',{exact:true}).selectOption('wait');
    plan=await postClick('/api/workflow/preview',page.locator('#workflow-preview'));assert.equal(plan.plan.steps.length,2);assert.ok(plan.plan.steps.every(step=>step.seconds===1));
    await page.locator('#workflow-add-type').selectOption('step');await page.locator('#workflow-add').click();let step=page.locator('#workflow-nodes>.workflow-node').nth(1);await step.getByLabel('技能',{exact:true}).selectOption('report');await step.getByLabel('条件类型',{exact:true}).selectOption('leaf');step=page.locator('#workflow-nodes>.workflow-node').nth(1);await step.getByLabel('引用前序节点 ID').fill('node1_2__node2');await step.getByLabel('结果',{exact:true}).selectOption('succeeded');
    plan=await postClick('/api/workflow/preview',page.locator('#workflow-preview'));assert.equal(plan.plan.steps.length,3);assert.equal(plan.plan.steps[2].condition.outcome,'succeeded');await shot('v3-workflow-desktop.png');checkpoints.push('form editor creates finite loops, child skills and typed prior-result conditions');

    await page.locator('#workflow-new').click();await page.locator('#workflow-parameters summary').click();await page.getByRole('button',{name:'添加模板参数',exact:true}).click();await page.locator('#workflow-add-type').selectOption('step');await page.locator('#workflow-add').click();step=page.locator('#workflow-nodes>.workflow-node').first();await step.getByLabel('目标地点',{exact:true}).selectOption('${parameter1}');await page.locator('#parameter-fields').getByLabel('默认值',{exact:true}).selectOption('storage');plan=await postClick('/api/workflow/preview',page.locator('#workflow-preview'));assert.equal(plan.plan.steps[0].target,'storage');checkpoints.push('typed template parameter form resolves a configured location in compiled plan');

    await switchView('lifecycle');await page.getByRole('button',{name:'停用',exact:true}).click();await page.locator('#lifecycle-state').filter({hasText:'inactive'}).waitFor();await page.getByRole('button',{name:'激活',exact:true}).click();await page.locator('#lifecycle-state').filter({hasText:'active'}).waitFor();assert.equal(await page.locator('#skills-catalog .skill-card').count(),14);checkpoints.push('fourteen skill capabilities and lifecycle deactivate/reactivate are visible');
    await switchView('data');await postClick('/api/data/backup',page.locator('#backup-create'));await postClick('/api/data/verify',page.locator('#backup-list .record-card').first().getByRole('button',{name:'校验',exact:true}));const manifestLink=page.locator('#backup-list .record-card').first().getByRole('link',{name:'下载校验清单',exact:true});const manifest=await page.request.get(url+await manifestLink.getAttribute('href'));assert.equal(manifest.status(),200);assert.ok((await manifest.json()).sha256);await page.locator('#policy-days').fill('90');await postClick('/api/data/policy',page.locator('#policy-form button'));await page.locator('#archive-before').fill('2000-01-01T00:00');const archive=await postClick('/api/data/archive',page.locator('#archive-preview'));assert.equal(archive.count,0);await postClick('/api/data/archive',page.locator('#archive-apply'));checkpoints.push('backup create/verify/manifest download, retention policy and zero-match soft-archive preview/apply pass');
    await switchView('history');await page.locator('#history-filter-query').fill('V3界面回归搜索修订');await page.locator('#history-filters button').click();await page.locator('#history-list .history-item').first().waitFor();checkpoints.push('history search form returns matching persisted task');
    await switchView('recovery');await page.locator('#recovery-mission').waitFor();assert.ok(await page.locator('#recovery-resume').isDisabled());checkpoints.push('recovery requires assessment and explicit checkbox before resume');
    await page.setViewportSize({width:390,height:844});for(const view of ['mission','history','settings','health','queue','workflows','memory','recovery','data','lifecycle']){await switchView(view);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`mobile overflow: ${view}`);}await shot('v3-mobile-capabilities.png');checkpoints.push('all ten mobile views fit 390 px width');
    assert.deepEqual(errors,[]);assert.deepEqual(network,[]);checkpoints.push('no page JavaScript errors or failed HTTP resources');
    const report={version:'7.0.0',generated_at:new Date().toISOString(),ok:true,backend:'real localhost mock service with explicitly enabled fixture skills',microphone:false,speaker:false,robot_hardware:false,checkpoints,screenshot_directory:process.env.UI_ARTIFACTS||null};if(process.env.UI_REPORT)fs.writeFileSync(process.env.UI_REPORT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
  }finally{await page.request.post(url+'/api/queue/control',{data:{action:'pause'}});await browser.close();}
}
run().catch(error=>{console.error(error);process.exitCode=1;});
