"use strict";
(() => {
  const U = window.PatrolUI, $ = id => document.getElementById(id);
  const E = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text !== undefined) n.textContent = String(text); return n; };
  const clone = value => JSON.parse(JSON.stringify(value));
  let config = null, skills = [], templates = [], templateId = null, nodeId = 1, recoveryPreview = null, archiveDraft = null;
  let workflow = {version:1,name:"三个地点查找水杯",steps:[{type:"search",id:"find",locations:["meeting_room","storage","reception"],object_name:"水杯",return_home:"always",continue_on:["not_found"]}],goal:{kind:"find_object",object_name:"水杯"}};
  const main = document.querySelector("main"), footer = document.querySelector(".page-footer");
  const notice = E("div", "workspace-notice"); notice.id = "workspace-notice"; notice.hidden = true; notice.setAttribute("role","status"); main.insertBefore(notice, $("view-mission"));
  const sections = {
    queue: `<div class="page-heading"><div><p class="eyebrow">ONE ROBOT. AN ORDERED DAY.</p><h1>有序执行，按时出发<span>。</span></h1><p class="subheading">队列统一协调动作；重启后等待操作员恢复调度。</p></div><button id="queue-refresh" class="button secondary">刷新队列</button></div><div class="workspace-columns"><section class="card"><h2>安排任务</h2><form id="queue-form" class="workspace-form"><label>任务来源<select id="queue-source"><option value="text">中文任务</option><option value="workflow">当前编排草稿</option></select></label><label>任务指令<textarea id="queue-text" rows="3">去会议室然后返回起点</textarea></label><div class="form-row"><label>优先级<input id="queue-priority" type="number" min="0" max="100" value="50"></label><label>首次执行时间<input id="queue-time" type="datetime-local"></label></div><label>重复方式<select id="queue-repeat"><option value="none">只执行一次</option><option value="interval">固定间隔</option><option value="daily">每日固定时间</option></select></label><div id="queue-interval-row" hidden><label>间隔秒数<input id="queue-interval" type="number" min="10" value="3600"></label></div><div id="queue-daily-row" class="form-row" hidden><label>每日时间<input id="queue-daily" type="time" value="09:00"></label><label>时区<select id="queue-timezone"><option>Asia/Hong_Kong</option><option>UTC</option></select></label></div><p class="help-text">首次时间按浏览器本地时区解释。错过的周期不连续补跑。</p><button class="button primary" type="submit">加入队列</button></form></section><section class="card"><div class="card-heading"><h2>调度队列</h2><span id="queue-state" class="quiet-tag">—</span></div><div class="toolbar"><button id="queue-pause" class="button secondary compact">暂停调度</button><button id="queue-resume" class="button primary compact">恢复调度</button></div><div id="queue-jobs" class="record-list"></div></section></div>`,
    workflows: `<div class="page-heading"><div><p class="eyebrow">A PLAN YOU CAN SHAPE.</p><h1>把流程，组织成可执行的步骤<span>。</span></h1><p class="subheading">用表单组合技能、条件分支和有限循环，再预览完整计划。</p></div><button id="workflow-new" class="button secondary">新建草稿</button></div><div class="workflow-layout"><section class="card"><div class="workspace-form"><label>流程名称<input id="workflow-name" value="三个地点查找水杯" maxlength="100"></label><div class="form-row"><label>任务目标<select id="workflow-goal"><option value="find_object">找到指定物体</option><option value="none">无独立目标</option></select></label><label>目标物体<input id="workflow-object" value="水杯"></label></div></div><div id="workflow-nodes" class="workflow-nodes"></div><div class="toolbar"><select id="workflow-add-type"><option value="step">技能步骤</option><option value="search">多地点查找</option><option value="repeat">有限循环</option><option value="if">条件分支</option></select><button id="workflow-add" class="button secondary compact">添加节点</button></div><div class="toolbar"><button id="workflow-preview" class="button secondary">预览编译计划</button><button id="workflow-submit" class="button primary">执行当前流程</button><button id="workflow-queue" class="button secondary">加入队列</button></div><div id="workflow-plan" class="compiled-plan" hidden></div><details class="raw-details"><summary>导入 / 导出流程 JSON</summary><textarea id="workflow-json" class="json-editor" rows="9"></textarea><div class="toolbar"><button id="workflow-export" class="button secondary compact">导出当前草稿</button><button id="workflow-import" class="button secondary compact">载入 JSON</button></div></details></section><aside class="card"><div class="card-heading"><h2>流程模板</h2><span id="template-selected" class="quiet-tag">未保存草稿</span></div><label class="stacked-label">模板说明<textarea id="template-description" rows="3" placeholder="适用场景与注意事项"></textarea></label><div class="toolbar"><button id="template-save" class="button primary compact">保存模板</button><button id="template-copy" class="button secondary compact">另存新模板</button></div><div id="templates-list" class="record-list"></div></aside></div>`,
    memory: `<div class="page-heading"><div><p class="eyebrow">EVIDENCE HAS A TIME AND PLACE.</p><h1>找回观察，保留依据<span>。</span></h1><p class="subheading">这里是历史观测，不代表物体当前仍在该位置。复查需要新任务。</p></div></div><section class="card"><form id="memory-form" class="filter-form"><label>物体<input id="memory-object" placeholder="例如：水杯"></label><label>地点<select id="memory-target"><option value="">全部地点</option></select></label><label>结果<select id="memory-outcome"><option value="">全部结果</option><option value="found">发现</option><option value="not_found">未发现</option><option value="inconclusive">无法确认</option></select></label><label>起始时间<input id="memory-since" type="datetime-local"></label><label>截止时间<input id="memory-until" type="datetime-local"></label><button class="button primary" type="submit">查找观测</button></form><p id="memory-summary" class="help-text"></p><div id="memory-results" class="record-list"></div></section>`,
    recovery: `<div class="page-heading"><div><p class="eyebrow">RESUME WITH CONTEXT.</p><h1>先核对，再继续<span>。</span></h1><p class="subheading">中断任务不自动重放；重新评估未完成步骤和旧观测条件。</p></div></div><section class="card"><div class="workspace-form"><label>中断任务<select id="recovery-mission"></select></label><button id="recovery-preview" class="button secondary">评估恢复计划</button></div><div id="recovery-assessment" class="compiled-plan"></div><label class="check-row"><input id="recovery-confirm" type="checkbox">我已核对上述计划，确认执行这次恢复</label><div class="toolbar"><button id="recovery-resume" class="button primary" disabled>确认恢复</button><button id="recovery-dismiss" class="button secondary">仅确认已知悉，不恢复</button></div></section>`,
    data: `<div class="page-heading"><div><p class="eyebrow">RECORDS YOU CAN KEEP.</p><h1>记录可追溯，数据可保全<span>。</span></h1><p class="subheading">备份完整数据库；软归档保留审计；准备恢复后需先关闭服务，再执行离线恢复命令。</p></div><button id="backup-create" class="button primary">创建备份</button></div><div class="workspace-columns"><section class="card"><h2>数据库备份</h2><div id="backup-list" class="record-list"></div><h3>准备恢复</h3><label class="stacked-label">选择备份<select id="restore-backup"></select></label><label class="check-row"><input id="restore-confirm" type="checkbox">已核对备份，理解需要先关闭服务再执行离线恢复命令</label><button id="restore-stage" class="button danger">校验并准备恢复</button><div id="backup-result" class="compiled-plan" hidden></div></section><section class="card"><h2>归档与保留策略</h2><form id="policy-form" class="workspace-form"><label>保留天数<input id="policy-days" type="number" min="1" max="3650" value="90"></label><label class="check-row"><input id="policy-auto" type="checkbox">启用自动软归档</label><button class="button secondary" type="submit">保存保留策略</button></form><hr><div class="workspace-form"><label>归档此时间之前的终态任务<input id="archive-before" type="datetime-local"></label><label>任务状态<select id="archive-states" multiple><option value="succeeded" selected>成功</option><option value="failed" selected>失败</option><option value="cancelled" selected>取消</option><option value="interrupted">中断</option></select></label><button id="archive-preview" class="button secondary">预览归档范围</button><p id="archive-preview-result" class="help-text"></p><button id="archive-apply" class="button primary" disabled>确认软归档</button></div></section></div>`,
    lifecycle: `<div class="page-heading"><div><p class="eyebrow">READY MEANS READY.</p><h1>明确能力，管理运行状态<span>。</span></h1><p class="subheading">未接入的外部能力会被明确拒绝；只有激活状态可以执行任务。</p></div><button id="lifecycle-refresh" class="button secondary">刷新能力</button></div><section class="card"><div class="card-heading"><h2>生命周期</h2><span id="lifecycle-state" class="mode-pill">—</span></div><p id="lifecycle-error" class="feedback"></p><div id="lifecycle-actions" class="toolbar"></div><details class="raw-details"><summary>状态转换记录</summary><pre id="lifecycle-transitions"></pre></details></section><div id="skills-catalog" class="skills-grid"></div>`
  };
  for (const [id, html] of Object.entries(sections)) { const section = E("section","workspace-view"); section.id=`view-${id}`; section.hidden=true; section.innerHTML=html; main.insertBefore(section,footer); }
  const historyFilters=E("form","filter-form history-filter");historyFilters.id="history-filters";historyFilters.innerHTML=`<label>搜索任务<input id="history-filter-query"></label><label>执行状态<select id="history-filter-state"><option value="">全部</option><option value="succeeded">成功</option><option value="failed">失败</option><option value="cancelled">取消</option><option value="interrupted">中断</option></select></label><label>起始时间<input id="history-filter-since" type="datetime-local"></label><label>截止时间<input id="history-filter-until" type="datetime-local"></label><label>归档状态<select id="history-filter-archived"><option value="false">未归档</option><option value="true">已归档</option></select></label><button class="button secondary" type="submit">筛选档案</button>`;$("view-history").insertBefore(historyFilters,document.querySelector(".history-layout"));historyFilters.onsubmit=event=>{event.preventDefault();void U.loadHistory();};
  const parameterPanel=E("details","raw-details");parameterPanel.id="workflow-parameters";parameterPanel.append(E("summary","","模板参数与默认值"));const parameterFields=E("div","workspace-form");parameterFields.id="parameter-fields";parameterPanel.append(parameterFields);$("workflow-nodes").before(parameterPanel);
  function inform(message, error=false) { notice.textContent=typeof message==="string"?message:JSON.stringify(message); notice.className=`workspace-notice ${error?"error":""}`; notice.hidden=false; }
  async function attempt(action) { try { return await action(); } catch(error) { inform(error.message,true); return null; } }
  const button = (label, fn, cls="secondary") => { const b=E("button",`button ${cls} compact`,label); b.type="button"; b.onclick=()=>void attempt(fn); return b; };
  function field(label,type,value,change,options) { const wrap=E("label","editor-field"); wrap.append(document.createTextNode(label)); const input=E(type==="select"?"select":type==="textarea"?"textarea":"input"); input.setAttribute("aria-label",label);if(type!=="select"&&type!=="textarea")input.type=type; if(options&&value&&typeof value==="string"&&value.startsWith("${")&&!options.some(item=>(Array.isArray(item)?item[0]:item)===value))options=[...options,[value,value]];if(options)for(const item of options){const [key,title]=Array.isArray(item)?item:[item,item]; const option=E("option","",title);option.value=key;input.append(option);}input.value=value??"";input.addEventListener(type==="select"?"change":"input",()=>change(type==="number"?Number(input.value):input.value));wrap.append(input);return wrap; }
  const outcomeNames={found:"已发现",not_found:"未发现",inconclusive:"无法确认",succeeded:"成功",failed:"失败",timed_out:"超时",skipped:"已跳过"};
  function parameterOptions(kind){return kind==="location"?placeOptions():kind==="object"?(config?.object_names||["水杯"]):undefined;}
  function parameterValueField(label,definition,value,change){const kind=definition.type;return field(label,kind==="location"||kind==="object"?"select":kind==="integer"||kind==="number"?"number":"text",value,change,parameterOptions(kind));}
  function renderParameters(){
    parameterFields.replaceChildren();
    for(const [name,definition]of Object.entries(workflow.parameters||{})){
      const row=E("div","record-card"),nameLabel=E("label","editor-field","参数名称"),nameInput=E("input");nameInput.value=name;nameInput.onchange=()=>{const next=nameInput.value.trim();if(!/^[A-Za-z][A-Za-z0-9_]{0,31}$/.test(next)||(next!==name&&workflow.parameters[next])){inform("参数名称必须唯一，并使用英文标识符。",true);nameInput.value=name;return;}if(next!==name){workflow.parameters[next]=definition;delete workflow.parameters[name];if(workflow.values&&name in workflow.values){workflow.values[next]=workflow.values[name];delete workflow.values[name];}const substitute=value=>typeof value==="string"?value.replaceAll("${"+name+"}","${"+next+"}"):Array.isArray(value)?value.map(substitute):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,substitute(item)])):value;workflow.steps=substitute(workflow.steps);}renderWorkflow();};nameLabel.append(nameInput);row.append(nameLabel);
      row.append(field("参数类型","select",definition.type,type=>{definition.type=type;definition.default=type==="location"?placeOptions()[0]?.[0]||"home":type==="object"?config?.object_names?.[0]||"水杯":type==="integer"||type==="number"?1:"文本";delete definition.min;delete definition.max;renderWorkflow();},[["location","已配置地点"],["object","已配置物体"],["text","文本"],["integer","整数"],["number","数值"]]),parameterValueField("默认值",definition,definition.default,value=>definition.default=value));
      if(["integer","number"].includes(definition.type))row.append(field("最小值","number",definition.min??-3600,value=>definition.min=value),field("最大值","number",definition.max??3600,value=>definition.max=value));
      row.append(E("p","help-text",`完整占位值：\${${name}}`),button("删除参数",()=>{delete workflow.parameters[name];if(workflow.values)delete workflow.values[name];renderWorkflow();}));parameterFields.append(row);
    }
    parameterFields.append(button("添加模板参数",()=>{workflow.parameters||={};let number=1;while(workflow.parameters[`parameter${number}`])number++;workflow.parameters[`parameter${number}`]={type:"location",default:placeOptions()[0]?.[0]||"home"};renderWorkflow();parameterPanel.open=true;}));
  }
  function placeOptions() { return Object.entries(config?.locations||U.getSnapshot()?.locations||{}).map(([id,p])=>[id,p.label||id]); }
  function defaultNode(type) { let id;do{id=`node${nodeId++}`;}while(JSON.stringify(workflow.steps).includes(`"id":"${id}"`)); if(type==="repeat")return{type,id,count:2,body:[]};if(type==="if")return{type,id,condition:{step_id:"",outcome:"found"},then:[],else:[]};if(type==="search")return{type,id,locations:placeOptions().slice(0,3).map(p=>p[0]),object_name:"水杯",return_home:"always",continue_on:["not_found"]};return{type:"step",id,kind:"navigate",target:placeOptions()[0]?.[0]||"home",on_failure:"abort"}; }
  function conditionEditor(condition,update,optional=true) {
    const box=E("div","condition-editor");const mode=!condition?"none":condition.all?"all":condition.any?"any":condition.not?"not":"leaf";
    box.append(field("条件类型","select",mode,value=>{const leaf={step_id:"",outcome:"found"};update(value==="none"?null:value==="leaf"?leaf:value==="not"?{not:leaf}:{[value]:[leaf]});renderWorkflow();},[...(optional?[["none","无条件"]]:[]),["leaf","步骤结果"],["all","全部满足"],["any","任一满足"],["not","不满足"]]));
    if(mode==="leaf")box.append(field("引用前序节点 ID","text",condition.step_id,v=>condition.step_id=v),field("结果","select",condition.outcome,v=>condition.outcome=v,Object.entries(outcomeNames)));
    if(mode==="not")box.append(conditionEditor(condition.not,v=>condition.not=v,false));
    if(mode==="all"||mode==="any") {condition[mode].forEach((child,i)=>{const row=E("div","condition-child");row.append(conditionEditor(child,v=>condition[mode][i]=v,false),button("移除",()=>{condition[mode].splice(i,1);renderWorkflow();}));box.append(row);});box.append(button("添加条件",()=>{condition[mode].push({step_id:"",outcome:"found"});renderWorkflow();}));}
    return box;
  }
  function renderNodes(nodes,container,depth=0) {
    if(depth>8){container.append(E("p","panel-error","嵌套过深，请简化流程。"));return;}
    nodes.forEach((node,index)=>{
      const card=E("div","workflow-node");card.dataset.nodeId=node.id;
      const head=E("div","node-head");head.append(E("strong","",{step:"技能步骤",search:"多地点查找",repeat:"有限循环",if:"条件分支"}[node.type]||node.type),E("span","quiet-tag",node.id||"未命名"));
      head.append(button("↑",()=>{if(index>0){[nodes[index-1],nodes[index]]=[nodes[index],nodes[index-1]];renderWorkflow();}}),button("↓",()=>{if(index<nodes.length-1){[nodes[index+1],nodes[index]]=[nodes[index],nodes[index+1]];renderWorkflow();}}),button("移除",()=>{nodes.splice(index,1);renderWorkflow();}));card.append(head);
      card.append(field("节点 ID","text",node.id,v=>node.id=v));
      if(node.type==="step") {
        const catalog=skills.length?skills:[{name:"navigate",label:"导航"},{name:"inspect",label:"检查"},{name:"wait",label:"等待"},{name:"report",label:"报告"},{name:"speak",label:"播报"}];
        card.append(field("技能","select",node.kind,value=>{node.kind=value;node.params={};delete node.seconds;delete node.object_name;if(value==="wait")node.seconds=1;const item=catalog.find(s=>s.name===value);if(item?.target==="none")delete node.target;else if(!node.target)node.target=placeOptions()[0]?.[0];renderWorkflow();},catalog.map(s=>[s.name,`${s.label||s.name}${s.available===false?" · 未接入":""}`])));
        const skill=catalog.find(s=>s.name===node.kind);
        if(skill?.target!=="none"&&node.kind!=="wait"&&node.kind!=="speak"&&node.kind!=="report")card.append(field("目标地点","select",node.target,v=>node.target=v,[...placeOptions(),...Object.entries(workflow.parameters||{}).filter(([,definition])=>definition.type==="location").map(([name])=>["${"+name+"}","参数："+name])]));
        if(node.kind==="inspect")card.append(field("物体（空白表示观察环境）","text",node.object_name,v=>node.object_name=v));
        if(node.kind==="wait")card.append(field("等待秒数","number",node.seconds||1,v=>node.seconds=v));
        const row=E("div","form-row");row.append(field("超时秒数","number",node.timeout??60,v=>node.timeout=v),field("最大重试次数","number",node.max_retries??0,v=>node.max_retries=v),field("失败后","select",node.on_failure||"abort",v=>node.on_failure=v,[["abort","终止任务"],["continue","记录失败并继续"]]));card.append(row);
        for(const [key,schema] of Object.entries(skill?.params_schema?.properties||{})){node.params ||= {};const type=schema.anyOf?"text":schema.enum?"select":schema.type==="integer"||schema.type==="number"?"number":schema.type==="boolean"?"select":schema.type==="array"||schema.type==="object"?"textarea":"text";const current=node.params[key]??schema.default??"";card.append(field((schema.title||key)+(schema.anyOf?"（JSON值，如 true、1、\"文本\"）":""),type,schema.anyOf?JSON.stringify(current):typeof current==="object"?JSON.stringify(current):current,v=>{try{node.params[key]=schema.anyOf||schema.type==="array"||schema.type==="object"?JSON.parse(v):schema.type==="boolean"?v==="true":v;}catch(_){inform(`${key} 必须为有效 JSON`,true);}},schema.enum|| (schema.type==="boolean"?[["false","否"],["true","是"]]:undefined)));}
        card.append(conditionEditor(node.condition,v=>{if(v)node.condition=v;else delete node.condition;}));
      } else if(node.type==="repeat") {
        card.append(field("循环次数","number",node.count,v=>node.count=v));const body=E("div","node-children");renderNodes(node.body||=[],body,depth+1);card.append(body);addNodeToolbar(card,node.body);
      } else if(node.type==="if") {
        card.append(conditionEditor(node.condition,v=>node.condition=v,false));for(const [key,label] of [["then","条件满足"],["else","条件不满足"]]){card.append(E("h4","",label));const body=E("div","node-children");renderNodes(node[key]||=[],body,depth+1);card.append(body);addNodeToolbar(card,node[key]);}
      } else if(node.type==="search") {
        card.append(field("查找物体","text",node.object_name,v=>node.object_name=v));const sites=E("div","search-sites");(node.locations||=[]).forEach((site,i)=>{const row=E("div","toolbar");row.append(field(`地点 ${i+1}`,"select",site,v=>node.locations[i]=v,placeOptions()),button("↑",()=>{if(i>0){[node.locations[i-1],node.locations[i]]=[node.locations[i],node.locations[i-1]];renderWorkflow();}}),button("移除",()=>{node.locations.splice(i,1);renderWorkflow();}));sites.append(row);});sites.append(button("添加查找地点",()=>{node.locations.push(placeOptions()[0]?.[0]||"home");renderWorkflow();}));card.append(sites,field("返回起点","select",node.return_home||"always",v=>node.return_home=v,[["always","结束后始终返回"],["found","仅找到后返回"],["never","不自动返回"]]));
        const outcomes=E("div","check-group");outcomes.append(E("span","","继续搜索下一个地点的条件："));for(const outcome of ["not_found","inconclusive"]){const label=E("label","check-row"),input=E("input");input.type="checkbox";input.checked=(node.continue_on||[]).includes(outcome);input.onchange=()=>{node.continue_on||=[];node.continue_on=input.checked?[...new Set([...node.continue_on,outcome])]:node.continue_on.filter(v=>v!==outcome);};label.append(input,document.createTextNode(outcomeNames[outcome]));outcomes.append(label);}card.append(outcomes);
      }
      container.append(card);
    });
  }
  function addNodeToolbar(parent,nodes) {const row=E("div","toolbar");const select=E("select");for(const [key,label]of [["step","技能"],["search","搜索"],["repeat","循环"],["if","分支"]]){const option=E("option","",label);option.value=key;select.append(option);}row.append(select,button("添加子节点",()=>{nodes.push(defaultNode(select.value));renderWorkflow();}));parent.append(row);}
  function renderWorkflow(){renderParameters();const box=$("workflow-nodes");box.replaceChildren();renderNodes(workflow.steps||=[],box);$("workflow-name").value=workflow.name||"";$("workflow-goal").value=workflow.goal?.kind||"none";$("workflow-object").value=workflow.goal?.object_name||"";$("template-selected").textContent=templateId?`模板 ${templateId.slice(0,8)}`:"未保存草稿";$("workflow-plan").hidden=true;}
  function planView(box,plan) {box.replaceChildren();box.hidden=false;box.append(E("strong","",plan?.summary||"已编译计划"));const list=E("ol","compiled-steps");for(const step of plan?.steps||[]){const li=E("li","",`${step.step_id||""} · ${step.kind} ${step.target?U.locationLabel(step.target):""}${step.object_name?" · "+step.object_name:""}`);if(step.condition)li.append(E("pre","condition-json",JSON.stringify(step.condition)));if(step.on_failure==="continue")li.append(E("span","branch-note","失败后继续后续步骤"));list.append(li);}box.append(list);}
  async function loadCommon(){const [c,s]=await Promise.all([U.api("/api/config"),U.api("/api/skills")]);config=c.config||c;skills=s.skills||[];}
  async function loadTemplates(){const result=await U.api("/api/templates");templates=result.templates||[];const list=$("templates-list");list.replaceChildren();for(const template of templates){const row=E("div","record-card");row.append(E("strong","",template.name),E("p","",template.description||""));const parameters={};for(const[name,definition]of Object.entries(template.workflow?.parameters||{})){parameters[name]=template.workflow.values?.[name]??definition.default;row.append(parameterValueField(`运行参数 ${name}`,definition,parameters[name],value=>parameters[name]=value));}const actions=E("div","toolbar");actions.append(button("载入编辑",()=>{templateId=template.id;workflow=clone(template.workflow);$("template-description").value=template.description||"";renderWorkflow();}),button("加入执行队列",async()=>{const result=await U.api(`/api/templates/${encodeURIComponent(template.id)}/run`,{request_id:crypto.randomUUID(),parameters});inform(result.message||"模板已加入队列");}),button("删除",async()=>{await U.api(`/api/templates/${encodeURIComponent(template.id)}`,{}, {method:"DELETE"});if(templateId===template.id)templateId=null;await loadTemplates();}));row.append(actions);list.append(row);}if(!templates.length)list.append(E("p","empty-log","保存一个流程，之后可以重复运行。"));}
  async function loadQueue(){const data=await U.api("/api/queue");$("queue-state").textContent=data.paused?"调度已暂停":"调度运行中";const list=$("queue-jobs");list.replaceChildren();for(const job of data.jobs||[]){const row=E("div","record-card"),status=job.state||job.status;row.dataset.jobId=job.id;row.append(E("strong","",job.name||job.summary||job.text||job.plan?.summary||job.workflow?.name||`任务 ${job.id}`),E("p","",`${status||"待执行"} · 优先级 ${job.priority??50} · ${job.run_at||job.next_run_at||"立即执行"}`));if(job.repeat)row.append(E("p","",`重复：${JSON.stringify(job.repeat)}`));if(job.last_error)row.append(E("p","panel-error",job.last_error));row.append(button("取消这条调度",async()=>{await U.api(`/api/queue/${encodeURIComponent(job.id)}/cancel`,{});await loadQueue();}));list.append(row);}if(!list.children.length)list.append(E("p","empty-log","队列为空。可以加入即时任务或明确安排未来时间。"));}
  async function loadMemory(){const query=new URLSearchParams({limit:"50"});for(const [key,id]of [["object_name","memory-object"],["target","memory-target"],["outcome","memory-outcome"],["since","memory-since"],["until","memory-until"]]){let value=$(id).value;if(value&&(key==="since"||key==="until"))value=new Date(value).toISOString();if(value)query.set(key,value);}const data=await U.api(`/api/memory?${query}`);$("memory-summary").textContent=typeof data.summary==="string"?data.summary:`${(data.observations||[]).length} 条历史观测 · 时间与来源见下方`;const list=$("memory-results");list.replaceChildren();for(const item of data.observations||[]){const row=E("div","record-card"),record=item.observation||item;row.append(E("strong","",`${record.object_name||"环境观测"} · ${U.locationLabel(record.target)} · ${outcomeNames[record.outcome]||record.outcome||"已记录"}`),E("p","",record.message||""),E("p","record-meta",`时间：${record.observed_at||record.created_at||"未提供"} · 来源：${typeof record.evidence==="object"?JSON.stringify(record.evidence):record.evidence||record.source||"外部接口"} ${record.simulated?"· 模拟数据":""}`));if(record.target)row.append(button("建立复查草稿",()=>{workflow={version:1,name:"核实历史观测",steps:[{type:"step",id:"visit",kind:"navigate",target:record.target},{type:"step",id:"observe",kind:"inspect",target:record.target,object_name:record.object_name||""}]};templateId=null;renderWorkflow();location.hash="workflows";inform("复查草稿已创建，尚未执行。请先预览。 ");}));list.append(row);}if(!list.children.length)list.append(E("p","empty-log","这个范围内没有历史观测。"));}
  async function loadRecoveries(){const groups=await Promise.all(["interrupted","failed","cancelled"].map(state=>U.api(`/api/history?state=${state}&limit=100`)));const data={missions:groups.flatMap(group=>group.missions||[]).filter(item=>!item.resumed_as)};const select=$("recovery-mission"),old=select.value;select.replaceChildren();const items=[...(data.missions||[]),...(U.getSnapshot()?.recoveries||[])],seen=new Set();for(const item of items){const id=typeof item==="string"?item:item.id||item.mission_id;if(!id||seen.has(id))continue;seen.add(id);const option=E("option","",`${item.summary||"中断任务"} · ${id.slice(0,8)}`);option.value=id;select.append(option);}if(seen.has(old))select.value=old;if(!select.children.length){const empty=E("option","","没有待评估的中断任务");empty.value="";select.append(empty);}}
  async function loadData(){const [backups,policyResponse]=await Promise.all([U.api("/api/data/backups"),U.api("/api/data/policy")]);const policy=policyResponse.policy||policyResponse;$("policy-days").value=policy.retention_days??90;$("policy-auto").checked=Boolean(policy.auto_archive);const list=$("backup-list"),select=$("restore-backup");list.replaceChildren();select.replaceChildren();for(const backup of backups.backups||[]){const id=backup.id||backup.backup_id;const row=E("div","record-card");row.append(E("strong","",backup.name||id),E("p","",`${backup.created_at||""} · ${backup.size_bytes??backup.size??"—"} bytes`));const link=E("a","button secondary compact","下载");link.href=`/api/data/backups/${encodeURIComponent(id)}/download`;link.download=backup.name||`backup-${id}.sqlite3`;const manifest=E("a","button secondary compact","下载校验清单");manifest.href=`/api/data/backups/${encodeURIComponent(id)}/manifest`;manifest.download=`${id}.json`;const actions=E("div","toolbar");actions.append(link,manifest,button("校验",async()=>{const result=await U.api("/api/data/verify",{backup_id:id});$("backup-result").hidden=false;$("backup-result").textContent=JSON.stringify(result,null,2);}));row.append(actions);list.append(row);const option=E("option","",backup.name||id);option.value=id;select.append(option);}if(!list.children.length)list.append(E("p","empty-log","还没有备份。"));}
  async function loadLifecycle(){const [response,catalog]=await Promise.all([U.api("/api/lifecycle"),U.api("/api/skills")]);const state=response.lifecycle||response;$("lifecycle-state").textContent=state.state||"未知";$("lifecycle-error").textContent=state.last_error?JSON.stringify(state.last_error):"";$("lifecycle-transitions").textContent=JSON.stringify(state.transitions||[],null,2);const actions=$("lifecycle-actions");actions.replaceChildren();for(const action of state.allowed_actions||[]){actions.append(button({configure:"配置",activate:"激活",deactivate:"停用",cleanup:"清理",reset_error:"重置错误",shutdown:"关闭"}[action]||action,async()=>{await U.api("/api/lifecycle",{action});await loadLifecycle();await U.refresh();}));}const list=$("skills-catalog");list.replaceChildren();for(const skill of catalog.skills||[]){const card=E("section",`card skill-card ${skill.available?"available":"unavailable"}`);card.append(E("h3","",skill.label||skill.name),E("span","quiet-tag",skill.available?skill.simulated?"模拟可用":"可用":"未接入"),E("p","",skill.description||""),E("p","help-text",skill.reason||""));const details=E("details","raw-details");details.append(E("summary","","参数约束"),E("pre","",JSON.stringify(skill.params_schema||{},null,2)));card.append(details);list.append(card);}}
  $("workflow-name").oninput=e=>workflow.name=e.target.value;$("workflow-goal").onchange=e=>{if(e.target.value==="none")delete workflow.goal;else workflow.goal={kind:"find_object",object_name:$("workflow-object").value};};$("workflow-object").oninput=e=>{if(workflow.goal)workflow.goal.object_name=e.target.value;};
  $("workflow-add").onclick=()=>{workflow.steps.push(defaultNode($("workflow-add-type").value));renderWorkflow();};$("workflow-new").onclick=()=>{workflow={version:1,name:"新的任务流程",steps:[]};templateId=null;renderWorkflow();};
  $("workflow-preview").onclick=()=>attempt(async()=>{const result=await U.api("/api/workflow/preview",{workflow});planView($("workflow-plan"),result.plan);inform("计划已编译，尚未执行。");});
  $("workflow-submit").onclick=()=>attempt(async()=>{const result=await U.api("/api/workflow/submit",{workflow,request_id:crypto.randomUUID()});inform(result.message||"流程已提交");await U.refresh();location.hash="mission";});
  $("workflow-queue").onclick=()=>attempt(async()=>{await U.api("/api/queue",{workflow,priority:50,request_id:crypto.randomUUID()});inform("当前流程已加入队列。");});
  $("workflow-export").onclick=()=>{$("workflow-json").value=JSON.stringify(workflow,null,2);};$("workflow-import").onclick=()=>attempt(async()=>{const value=JSON.parse($("workflow-json").value);await U.api("/api/workflow/preview",{workflow:value});workflow=value;templateId=null;renderWorkflow();inform("已加载通过校验的流程。");});
  async function saveTemplate(copy){const data={name:workflow.name,description:$("template-description").value,workflow};const result=await U.api(templateId&&!copy?`/api/templates/${encodeURIComponent(templateId)}`:"/api/templates",data,{method:templateId&&!copy?"PUT":"POST"});templateId=result.template?.id||result.id||templateId;await loadTemplates();renderWorkflow();inform("模板已保存。");}
  $("template-save").onclick=()=>attempt(()=>saveTemplate(false));$("template-copy").onclick=()=>attempt(()=>saveTemplate(true));
  $("queue-repeat").onchange=()=>{$("queue-interval-row").hidden=$("queue-repeat").value!=="interval";$("queue-daily-row").hidden=$("queue-repeat").value!=="daily";};
  $("queue-form").onsubmit=e=>{e.preventDefault();attempt(async()=>{const body={priority:Number($("queue-priority").value),request_id:crypto.randomUUID()};if($("queue-source").value==="workflow")body.workflow=clone(workflow);else body.text=$("queue-text").value;if($("queue-time").value)body.run_at=new Date($("queue-time").value).toISOString();if($("queue-repeat").value==="interval")body.repeat={interval_seconds:Number($("queue-interval").value)};if($("queue-repeat").value==="daily")body.repeat={daily_at:$("queue-daily").value,timezone:$("queue-timezone").value};await U.api("/api/queue",body);await loadQueue();inform("调度任务已保存。");});};
  $("queue-refresh").onclick=()=>attempt(loadQueue);for(const action of ["pause","resume"])$("queue-"+action).onclick=()=>attempt(async()=>{await U.api("/api/queue/control",{action});await loadQueue();});
  $("memory-form").onsubmit=e=>{e.preventDefault();attempt(loadMemory);};
  $("recovery-preview").onclick=()=>attempt(async()=>{const id=$("recovery-mission").value;if(!id)throw new Error("没有可评估的任务");recoveryPreview=await U.api("/api/recovery/preview",{mission_id:id});const box=$("recovery-assessment");box.replaceChildren(E("pre","",JSON.stringify(recoveryPreview.assessment,null,2)));if(recoveryPreview.plan){const plan=E("div","");planView(plan,recoveryPreview.plan);box.append(plan);}$("recovery-confirm").checked=false;$("recovery-resume").disabled=true;});
  $("recovery-confirm").onchange=()=>{$("recovery-resume").disabled=!$("recovery-confirm").checked||!recoveryPreview?.plan;};$("recovery-mission").onchange=()=>{recoveryPreview=null;$("recovery-confirm").checked=false;$("recovery-resume").disabled=true;};
  $("recovery-resume").onclick=()=>attempt(async()=>{if(!$("recovery-confirm").checked||!recoveryPreview?.plan)throw new Error("请先评估并确认计划");const result=await U.api("/api/recovery/resume",{mission_id:$("recovery-mission").value,confirmed:true,request_id:crypto.randomUUID()});inform(result.message||"恢复计划已提交");await U.refresh();location.hash="mission";});
  $("recovery-dismiss").onclick=()=>attempt(async()=>{await U.api("/api/recovery",{mission_id:$("recovery-mission").value,action:"dismiss"});await loadRecoveries();await U.refresh();inform("已记录知悉，没有恢复任务。");});
  $("backup-create").onclick=()=>attempt(async()=>{await U.api("/api/data/backup",{});await loadData();inform("备份已创建。");});
  $("restore-stage").onclick=()=>attempt(async()=>{if(!$("restore-confirm").checked)throw new Error("请先确认备份与重启要求");const backup_id=$("restore-backup").value;if(!backup_id)throw new Error("请选择备份");await U.api("/api/data/verify",{backup_id});const result=await U.api("/api/data/restore",{backup_id,confirmed:true});$("backup-result").hidden=false;$("backup-result").textContent=JSON.stringify(result,null,2);inform("已准备恢复文件。请关闭当前服务，再按下方提示运行 --restore-backup 命令；普通重启不会应用恢复。");});
  $("policy-form").onsubmit=e=>{e.preventDefault();attempt(async()=>{await U.api("/api/data/policy",{retention_days:Number($("policy-days").value),auto_archive:$("policy-auto").checked},{method:"PUT"});inform("保留策略已保存。");});};
  function archiveValues(){if(!$("archive-before").value)throw new Error("请选择归档截止时间");return{before:new Date($("archive-before").value).toISOString(),states:Array.from($("archive-states").selectedOptions).map(option=>option.value)};}
  $("archive-preview").onclick=()=>attempt(async()=>{archiveDraft=archiveValues();const result=await U.api("/api/data/archive",{...archiveDraft,dry_run:true});$("archive-preview-result").textContent=JSON.stringify(result);$("archive-apply").disabled=false;});
  for(const id of ["archive-before","archive-states"])$(id).onchange=()=>{archiveDraft=null;$("archive-apply").disabled=true;};
  $("archive-apply").onclick=()=>attempt(async()=>{if(!archiveDraft||JSON.stringify(archiveDraft)!==JSON.stringify(archiveValues()))throw new Error("归档范围已变更，请重新预览");const result=await U.api("/api/data/archive",{...archiveDraft,dry_run:false});archiveDraft=null;$("archive-apply").disabled=true;inform(result.message||JSON.stringify(result));});
  $("lifecycle-refresh").onclick=()=>attempt(loadLifecycle);
  window.addEventListener("patrol:view",event=>{notice.hidden=true;const view=event.detail;attempt(async()=>{if(view==="queue")await loadQueue();if(view==="workflows"){await loadCommon();renderWorkflow();await loadTemplates();}if(view==="memory"){await loadCommon();const select=$("memory-target"),old=select.value;select.replaceChildren();const empty=E("option","","全部地点");empty.value="";select.append(empty);for(const[id,label]of placeOptions()){const option=E("option","",label);option.value=id;select.append(option);}select.value=old;await loadMemory();}if(view==="recovery")await loadRecoveries();if(view==="data")await loadData();if(view==="lifecycle")await loadLifecycle();});});
  window.PatrolWorkflow = {snapshot: () => clone(workflow)};
  renderWorkflow();U.switchView(location.hash.slice(1)||"mission");
})();
